name: CI-gitleaks
on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

jobs:
  asciidoctor_job:
    runs-on: ubuntu-latest
    name: Scan secrets using gitleaks
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      #----------------------------------------------
      #               scan secrets
      #----------------------------------------------
    - name: gitleaks
      run: |
        gitleaks detect -v --redact
    - name: gitleaks2
      run: |
        gitleaks detect -v --redact
