name: CI-gitleaks
on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

jobs:
  asciidoctor_job:
    runs-on: self-hosted
    name: Terraform
    steps:
    - name: terraform plan
      run: |
        terraform plan
    - name: terraform apply
      run: |
        terraform apply --auto-approve
