name: "Check version"

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
    paths-ignore:
      - 'README.md'

jobs:
  terraform:
    name: "Check version"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current version
        id: check-current-version
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0)
          echo ${CURRENT_VERSION}

      - name: Get new version
        id: check-new-version
        run: |
          NEW_VERSOIN=$(cat version.json | jq -r '.version')

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install semver
        run: npm install semver

      - name: Compare versions
        env:
          CURRENT_VERSION: ${{ steps.check-current-version.outputs.result }}
          NEW_VERSOIN: ${{ steps.check-new-version.outputs.result }}
        run: |
          node -e "
          const semver = require('semver');
          const currentVer = process.env.CURRENT_VERSION;
          const newVer = process.env.NEW_VERSOIN;
          
          if (semver.gt(newVer, currentVer)) {
            process.exit(0);
          } else {
            console.log(`\${newVer} is older or  same as \${currentVer}`);
          }"
