name: "Push tag and create release note"

on:
  push:
    branches:
      - 'main'

jobs:
  terraform:
    name: "Push tag and create release note"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get new version
        run: |
          NEW_VERSION=$(cat version.json | jq -r '.version')
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Push git tag
        run: |
          git tag ${NEW_VERSION}
          git push origin ${NEW_VERSION}
  
      - name: Create release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: release-drafter/release-drafter@v6
        with: 
          config-name: release-drafter.yml
